telegram:
  api_token: 'YOUR_BOT_API_KEY'
  chat_id: 'YOUR_CHAT_ID'

messages:
  system_start: "System started and ready to receive doorbell signals."
  doorbell_ring: "Someone rang the doorbell!"
  system_shutdown: "The system is shutting down."
  gpio_cleanup: "GPIO pins have been reset and the system has stopped."
