telegram:
  enabled: true  # Option to enable/disable Telegram
  api_token: 'YOUR_TELEGRAM_BOT_API_KEY'
  chat_id: 'YOUR_CHAT_ID'

discord:
  enabled: true  # Option to enable/disable Discord
  bot_token: 'YOUR_DISCORD_BOT_TOKEN'
  channel_id: 'YOUR_DISCORD_CHANNEL_ID'

settings:
  enable_cmd_prints: true  # Toggle to enable/disable console prints
  log_message_send: true  # Toggle to enable/disable logging message send status
  gpio_pin: 17  # Define the GPIO pin number here

print_messages:
  system_start_print: "System started and waiting for the doorbell signal."
  doorbell_ring_print: "Doorbell was pressed!"
  system_shutdown_print: "System is shutting down..."
  gpio_cleanup_print: "GPIO cleanup done and system is stopped."

telegram_messages:
  system_start: "ℹ️ Important Information\n\nThe doorbell system has started!"
  doorbell_ring: "💥 Important Information 💥\n\nThe doorbell has rung!"
  system_shutdown: "ℹ️ Important Information\n\nThe system is shutting down!"
  gpio_cleanup: "ℹ️ Important Information\n\nThe system has been powered off."

discord_messages:
  system_start: "The doorbell system has started!"
  doorbell_ring: "The doorbell has rung!"
  system_shutdown: "The system is shutting down!"
  gpio_cleanup: "The system has been powered off."
